### ISSUE TITLE
PomBase genes and Intermine genes not  fully aligned

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#1]
I had a little play!

I tried to import a list, so that I have a list to play with.
This list is 98 genes involved in cytokinesis:
[gene_list (82).txt](https://github.com/intermine/pombemine/files/7136549/gene_list.82.txt)

These are the unique primary Ids.

I get this message:
<img width="1199" alt="Screenshot 2021-09-09 at 13 39 33" src="https://user-images.githubusercontent.com/7359272/132687890-7d8c57a6-f836-4395-9f65-aba3b249e8f4.png">

and am asked to resolve the 3 ids above
and these:

<img width="1186" alt="Screenshot 2021-09-09 at 13 40 28" src="https://user-images.githubusercontent.com/7359272/132687972-2a8a2aac-1254-4b88-a8ba-36cc206530bd.png">

This seems odd as there should be no conflicts for systematic identifiers?

**Comment by rachellyne** [comment]
Hi Val,

It looks like probably an integration issue with the BioGrid data - I will investigate further.

**Comment by danielabutano** [comment]
@ValWood I have fixed and redeployed the webapp. Please have a look at it!

**Comment by ValWood** [comment]
Perfect, thanks!
