### ISSUE TITLE
Add a button to PomBase for sending genes to PombeMine

### ISSUE THREAD

**Issue by kimrutherford** [intermine/pombemine#11]
Could you let me know what API to use to send a list to InterMine?

Thanks!

**Comment by danielabutano** [comment]
@kimrutherford the new interface BG do not provide yet the /portal.do endpoint which is offered by the legacy webapp.
But we have a [ticket](https://github.com/intermine/bluegenes/issues/735) for that with more details

**Comment by danielabutano** [comment]
@kimrutherford BG has implemented the portal.do endpoint.
Try [this](http://met1.gen.private.cam.ac.uk:5050/pombemine/portal.do?externalids=A1BG,NAT2,ADA&class=Gene) with your browser
'http://met1.gen.private.cam.ac.uk:5050/pombemine/portal.do?externalids=A1BG,NAT2,ADA&class=Gene'
Optional parameter
extraValue=S.+pombe

You can call the endpoint using the input form. In the ticket [here](https://github.com/intermine/bluegenes/issues/735) an example

**Comment by kimrutherford** [comment]
Thanks Daniela.  Your examples work for me.

I'll make the PomBase code changes once this is done: intermine/bluegenes#792

**Comment by kimrutherford** [comment]
> I'll make the PomBase code changes once this is done: https://github.com/intermine/bluegenes/issues/792

That's done now.

**Comment by kimrutherford** [comment]
For @ValWood and @manulera:

Maybe there are enough buttons at the top right of the results page and adding another isn't a good idea.  But what do you think?

Another option is to rename the "Visualise" menu to "Tools" and add a new menu item for "Send list to PombeMine".

Any other ideas?


![result-buttons-1](https://user-images.githubusercontent.com/90474/169020687-efda6cc2-4406-43b8-ba3e-cf638ecabe6b.png)

**Comment by ValWood** [comment]
Or, change "Download" button to "Export to..." and that could be options
Download
Export to PombeMine

**Comment by kimrutherford** [comment]
> Or, change "Download" button to "Export to..." and that could be options

That makes sense.  Currently "Download..." is a button that opens the download dialog.  We could make "Export:" a menu with "Download" and "Send to PombeMine" as items.

**Comment by kimrutherford** [comment]
>  We could make "Export:" a menu with "Download" and "Send to PombeMine" as items.

Sorry Val.  I see that I just repeat back what you said back to you!  I blame the fever.

**Comment by kimrutherford** [comment]
I think the code is ready to go for this feature.  It's a bit hard to test because of the problems uploading a list on the PombeMine side (https://github.com/intermine/bluegenes/issues/735#issuecomment-1130798844)

I'm wondering what to do for japonicusdb.org.  There isn't a Mine so an Export menu would just contain "Download..."  It might be best to leave JaponicusDB as it is.

**Comment by kimrutherford** [comment]
How's this?:

![export-menu-1](https://user-images.githubusercontent.com/90474/169724493-b30926c5-861e-48c6-a12d-f879b4d477a3.png)

**Comment by ValWood** [comment]
I did not notice! I blame post-covid brain fog.  

Yes, exactly. Added bonus (or not) is that more people will see it.

**Comment by ValWood** [comment]
> I'm wondering what to do for japonicusdb.org. There isn't a Mine so an Export menu would just contain "Download..." It might be best to leave JaponicusDB as it is.

Probably, if it is easy to configure. There was talk of doing a japoniccus MIne too but I don't want to get side-tracked by that. It should be straightforward, but of course it never I,s and it would be extra work to configure etc. If there is a demand it could be done in future.

**Comment by kimrutherford** [comment]
> > It might be best to leave JaponicusDB as it is.
>
> Probably, if it is easy to configure. 

Yep!  I implemented it such that if no Mine is configured, we just have a "Download..." button like always.  If there is a Mine configured, it shows a menu with two items.  So japonicusdb.org won't changed look until (if ever) there is a Mine for it.

The current status is that the code is finished (I think) and committed, but I haven't added the configuration for PomBase to enable it.  I'll add the config when PombeMine it fixed so we can test it.

**Comment by danielabutano** [comment]
@kimrutherford [pombemine](http://pombemine.rahtiapp.fi/pombemine) uses BG 1.4.2 whch contains the support for HTTP clients using POST portal.do. Anything else that needs to be fixed?

**Comment by kimrutherford** [comment]
Hi @danielabutano  @heralden 

I just tested POSTing a list to portal.do and it works perfectly.  Thanks very much!
