### ISSUE TITLE
(BJ) Items to remove from the drop down menu for Pombemine

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#14]
These will never be annotated for fission   yeast of provided by PomBase, so to display them will be confusing for users:

cDNA clone
Chromosomal Deletion
Chromosomal Duplication
Chromosomal inversion
Chromosomal Translocation
Chromosomal transposition
Chromosome based
Chromosome structure variation
Component (we will not import because it is a small amount of arbitrary /inconsistent data)
Oligo
EST
Primer
Reverse primer
Golden path fragment
PCR product
Overlapping EST set
Enhancer ( not relevant for yeast, could be taxon restricted)
Sequence collection
Ortholog evidence code (unless this refers to source, currently it is not populated- we were going to load orthologs from other sources too?)

We might use these in the distant future, but better not to display things for which data is unavailable:
Synteny block
Syntenic region
Transposable element insertion site
TF binding site
Strain
Sequence variant

**Comment by ValWood** [comment]
It is also not  good to display the groupining terms for 
"Ontologies"
Ontology annotation
Ontology evidence code
etc

It doesn't make sense to do a query  to return all as  GO terms and phenotypes are distinct (apples and oranges). Also  phenotypes are associated with alleles, and GO terms are associated with genes and they have different metadata.  So having this as an entry point from a menu doesn't make sense.

**Comment by danielabutano** [comment]
> These will never be annotated for fission yeast of provided by PomBase, so to display them will be confusing for users:
> 
> cDNA clone Chromosomal Deletion Chromosomal Duplication Chromosomal inversion Chromosomal Translocation Chromosomal transposition Chromosome based Chromosome structure variation Oligo EST Primer Reverse primer Golden path fragment PCR product Overlapping EST set Enhancer ( not relevant for yeast, could be taxon restricted) Sequence collection Ortholog evidence code (unless this refers to source, currently it is not populated- we were going to load orthologs from other sources too?)
> 
> We might use these in the distant future, but better not to display things for which data is unavailable: Synteny block Syntenic region Transposable element insertion site TF binding site Strain Sequence variant
Yes @ValWood you are right.
BG interface shows all the classes defined in the model, instead to show only the classes that have data (as the old interface does). We need to improve it?
@uosl do we have a ticket on BG for that?

**Comment by uosl** [comment]
> BG interface shows all the classes defined in the model, instead to show only the classes that have data (as the old interface does). We need to improve it

@danielabutano This has been explored in the past and it doesn't seem to be doable to have it like the old UI querybuilder with the current web services (see last comment in https://github.com/intermine/bluegenes/issues/662).

**Comment by ValWood** [comment]
That's a shame. I think it is really confusing to have lots of data types visible that are not relevant to the resource. For many of these, it isn't immediately obvious what they are either from the labels so the user needs to click on them to see if there is data. Also some data classes (like evidence code) do not make a useful starting point for queries and so this is also misleading.

Presumably, the  drop done menu could be made configurable. In fact, it must already be configurable be to some extent because  there are some data types that we intend to load that are not yet visible as classes (modification), and some datatypes that would not be relevant for other species (PECO- this will be removed for PomBase, it's not the correct namespace)


For example near to the top of the list here:
<img width="338" alt="Screenshot 2022-01-24 at 09 20 25" src="https://user-images.githubusercontent.com/7359272/150755324-6464082e-7cb8-42dd-a353-29ef9df8b1c4.png">

...only 3 data classes will ever be relevant. 
It will be very difficult for bench biologise users  to get to grips with the interface if these are not hidden.

**Comment by uosl** [comment]
I may have misunderstood. I was thinking of the model browser tree, where the old UI will hide class nodes that don't have any data.

For the root classes which are displayed in the dropdown, it's easy to tell which are populated or not, so those can be hidden. I have created a ticket for this here: https://github.com/intermine/bluegenes/issues/770

**Comment by ValWood** [comment]
Cool, the model browser tree is not such an issue because here it is obvious what is populated and what isn't. It would be nice if the non-populated data types were slightly greyed out.  With the  current blue/ black distinction  it isn't so immediately obvious, especially at the top of the model:


<img width="447" alt="Screenshot 2022-01-24 at 11 05 33" src="https://user-images.githubusercontent.com/7359272/150771745-2183d88c-30d2-4d99-be71-c74f4369c59c.png">

A user could easily think that only the 'high-level' classes were blue. it takes a bit of browsing to figure out  that only populated classes are blue.

**Comment by uosl** [comment]
I agree it would be better if these were light grey rather than black. Created a ticket for this: https://github.com/intermine/bluegenes/issues/775

**Comment by danielabutano** [comment]
The new BG version fixed it

**Comment by ValWood** [comment]
Hi we are nt seeing this fix. Unless  I misunderstood what was happening here. We still see all of the unused datatypes  looking normal in the menu.

All of us found this really confusing.

Will reopen, and can discuss  if required.

@manulera
@kimrutherford

**Comment by ValWood** [comment]
I think we were talking at cross purposes.
We were hoping that the classes that are not populated would not appear in this menu:

<img width="392" alt="Screenshot 2022-05-23 at 21 03 56" src="https://user-images.githubusercontent.com/7359272/169897527-c285a795-c087-4f83-a146-15cef84b167f.png">

**Comment by ValWood** [comment]
Closing, it is much better. I don't think anything can be done about displaying populated terms.

**Comment by ValWood** [comment]
AT the very bottom of the page it says "Admin mode", but I don't see where to go...

**Comment by kimrutherford** [comment]
Hi Val.  I see lots of "Add tags" buttons.  If you don't try going to: http://legacy.pombemine.rahtiapp.fi/pombemine/tree.do 

![add-tags-1](https://user-images.githubusercontent.com/90474/170121983-507f9ab1-9087-4345-a40e-37ce3cbf660e.png)

**Comment by ValWood** [comment]
I do see that. But in that list I do not see any. of the terms that I want to add to the 'top group' (this would be all of the terms we have used to begin queries so far

GO
phenotype
allele

etc

And I don'ts ee any way to drill down (if they are hidden)

**Comment by kimrutherford** [comment]
> And I don'ts ee any way to drill down (if they are hidden)

They seem to be mosltly underneath "Annotatable":

![add-tags-2](https://user-images.githubusercontent.com/90474/170144258-46ae80d9-a85c-427d-b53d-65071be5d68a.png)
