### ISSUE TITLE
(BJ) Data to remove (PECO) and conditions

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#15]
PECO is the old name for our conditions ontology.  The ontology prefix should  be updated to FYECO in future data releases (there was a namespace clash with PECO, the plant evidence ontology) so we needed to change it.

The data that is currently  loaded is the plant evidence code ontology.

I don't think we need to include FYECO in the drop-down anyway ( this isn't a formal OBO ontology, we hide this acronym from our users, it is only really used behind the scenes.

Instead this data would be available under. the "condition" datatype (this is a more readable label).

Esentially for fission yeast FYECO/PECO(old)/condition are  different ways of describing the same datatype.

**Comment by ValWood** [comment]
Edited about to make it clearer.

**Comment by rachellyne** [comment]
Ahh - I think the ontology name has just been put in wrong.  The data is pombe!

**Comment by ValWood** [comment]
Yep the terms are ours, 

it is when I click on the "conditions" in the dropdown menu that I see reference to the plant PECO:
<img width="1162" alt="Screenshot 2022-01-24 at 15 39 27" src="https://user-images.githubusercontent.com/7359272/150814582-a9d1ab8a-9a26-470c-8771-ffe0b767b398.png">
but this should probably go away once  the mine is refreshed as we will no longer reference PECO?

The label in the drop-down could be just "phenotype conditions ontology" ( instead of PECO TERM) We don't need to say FYECO as we don't make that public,and it isn't an obo foundry ontology.

**Comment by rachellyne** [comment]
@val I presume the ontology we now need is fyeco.obo from here:
https://github.com/pombase/fypo

We have the updated term ids loaded but did not update the ontology so they have not merged.

**Comment by ValWood** [comment]
Yep that is the correct source.  
@kimrutherford anything else  Intermine need to be aware of here?

My feeling is that this should not be treated as an 'ontology' as such. It is really just a flat vocabulary. We store it in obo format for convenience. When we use 'conditions' that have more in common with annotation extensions.  I guess we can wait and see what the queries look like ;)

**Comment by danielabutano** [comment]
Fixed
![image](https://user-images.githubusercontent.com/1678179/154535035-ce71d88e-caa4-47f4-b26a-e67ed1ed1f41.png)
