### ISSUE TITLE
(BJ) RNA types

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#17]
Queries on RNA types retrieve no data.
RNA types should be included in the json file @kimrutherford ?

includes
tRNA
snRNA
snoRNA
rRNA

**Comment by ValWood** [comment]
This might be becasue SO term identifiers are not loading?
Only  SO terms names are visible. The visible set is only a subset of the  ones we use related to the annotation objects in the sequence contig files.

We also add SO terms to features (like RNAs) to describe their type.  @kimrutherford  can confirm if these are exported.

**Comment by kimrutherford** [comment]
> We also add SO terms to features (like RNAs) to describe their type. @kimrutherford can confirm if these are exported

The SO term names of each gene are exported in the "feature_type" field, kind of.  The term name we use has a space instead of an underscore ("snRNA gene" instead of snRNA_gene for SO:0001268).  We don't currently export the SO term ID, but that's straightforward to add.

https://github.com/pombase/pombase-chado/issues/842

**Comment by rachellyne** [comment]
I'm not sure why these haven't loaded. We have added a feature type attribute to the gene class but it's empty!  I think it should be a simple fix.

**Comment by danielabutano** [comment]
yes, my fault. Instead to take the  "feature_type" field I used "featureType". I will fix it.
Only a question. when we have  2 values (e.g. mRNA gene) do you want both ?

**Comment by kimrutherford** [comment]
> Only a question. when we have 2 values (e.g. mRNA gene) do you want both ?

I think we should have the whole string "mRNA gene" because that's similar to the term name in SO.

**Comment by ValWood** [comment]
Yes. IIRC the cognate SO terms always have an underscore mRNA_gene (which always confuses me- most ontologies don't do this)

**Comment by danielabutano** [comment]
Fixed!
