### ISSUE TITLE
(BJ) protein domain region query

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#19]
returns no results

**Comment by danielabutano** [comment]
we return valu for protein domain but not for protein domani region..is it correct @rachellyne ?

**Comment by rachellyne** [comment]
There was a loading problem with this - same as BioGrid, but hopefully fixed.

**Comment by danielabutano** [comment]
Fixed
![image](https://user-images.githubusercontent.com/1678179/154534344-64f39bb5-0690-41a8-a60a-074020cb6d27.png)
