### ISSUE TITLE
UniProtEntry suggestion

### ISSUE THREAD

**Issue by kimrutherford** [intermine/pombemine#2]
I promised to make an issue about this.  Here's is a dodgy diagram with my suggested model.  I think we should only gets things from UniProt that are useful and that aren't curated in PomBase.

![pombemine-uniprotentry-1](https://user-images.githubusercontent.com/90474/134156701-a3cff7e1-b1da-442c-a88e-eed1730b5bc5.png)

**Comment by rachellyne** [comment]
Thanks Kim - that is what I thought you meant.  We should go through the Uniprot stuff we get and see what you want.

**Comment by danielabutano** [comment]
redeployed with the new model
