### ISSUE TITLE
(BJ) phenotype data

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#21]
Currently displays as 
<img width="731" alt="Screenshot 2022-01-21 at 15 40 12" src="https://user-images.githubusercontent.com/7359272/150556226-078305f4-4aa9-46d7-9ac1-986871859351.png">

**Comment by ValWood** [comment]
Phenotype data should be

term
termID
term (phenotype)  description
allele
penetrance
Expressivity

Penetrance will be one of 3 qualifiers (high/medium or low)
Or a numberral which is always reported as a %

Note: penetrance numbers look odd. I'm not aware of any under around 5% I need to check the ones above if you can let me know the source.

**Comment by danielabutano** [comment]
I think it's better to create a template for this @rachellyne 
Here are the data
![image](https://user-images.githubusercontent.com/1678179/150565749-58279d1c-ed44-4db4-b78f-76cb64d5a98f.png)

**Comment by ValWood** [comment]
@rachellyne  we can have a look at this next week.

**Comment by rachellyne** [comment]
@val yes let's look togther.  It all looks correct according to the data we have in the file - there are a few with lower penetrance.

**Comment by ValWood** [comment]
Right I will check the V. low penetrance data at our end. That smells funny, it's probably annotation errors.

**Comment by ValWood** [comment]
OK the data is OK. I fixed a couple of things.

One small change. Is it possible to label the "phenotype" class as "phenotype (%)"
Or we should display each number as 0.1% 1% etc. I think it is better to keep just numerical values and change the headings in case it is possible to do queries based on numerical ranges?)

**Comment by danielabutano** [comment]
@ValWood could you confirm that you mean to rename "phenotype" class into "phenotype (%)" and not "penetrance" attribute into  "penetrance (%)"

**Comment by ValWood** [comment]
Oops sorry that should be penetrance (%)!

**Comment by danielabutano** [comment]
Fixed
![image](https://user-images.githubusercontent.com/1678179/154534775-f7e4ae73-5d46-4dfc-a7e0-712a961a0890.png)
