### ISSUE TITLE
(BJ) possible bug in GO publication filtering

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#22]
In query builder:
If I do query:

<img width="1228" alt="Screenshot 2022-01-28 at 11 59 49" src="https://user-images.githubusercontent.com/7359272/151543459-5b8986b8-ddfa-4dc9-a01c-79a412778e76.png">

and them remove "publication" I get

XML is well formatted but query contains errors:
Outer join status path GOAnnotation.evidence.publications is not relevant to the query.

It only occurs is I remove publications before I toggle off the outer join?

**Comment by danielabutano** [comment]
@ValWood yes it seems a bug to me too. @uosl did you know about it? do you want me to create a ticket in BG?

**Comment by uosl** [comment]
No, didn't know about this. I created an issue: https://github.com/intermine/bluegenes/issues/774

**Comment by danielabutano** [comment]
The new BG version fixed this issue
