### ISSUE TITLE
publication number

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#24]
~60,000 publications are loaded.
We can't figure out where they come from. 
@kimrutherford exports. 11700  with fission yeast specific data. We think this is pretty much all publications relevant to fission yeast (plus a few others that are used in annotation for some reason).

It may be that publications are loaded from other pipelines? This will affect any analysis (background set) using Mesh terms (for example)

**Comment by rachellyne** [comment]
This will contain every single publication loaded, including all from BioGrid, UniProt etc so will be greater than the number just in pombase.

**Comment by ValWood** [comment]
Should all of the publications be relevant to fission yeast (or would this include publications for other species)?  
Do we load  biogrid interaction data for S. cerevisiae or human? I didn't think we did.

 If we are only loading fission yeast associated publications (from any source) the number should only begin with  ~12-13000 not 60,000 so does this include publications that are nothing to do with fission yeast ?  (I understand that there might be papers that are not from pombase, but PomBase contains all fission yeast related literature whether curated or not).

**Comment by ValWood** [comment]
These come mainly frm InterPro and Uniprot. POmbase curated publications are not currently included. these will be included in the export in the near future.
