### ISSUE TITLE
pipe separator for some  GO IDs in the "with/from" field with IC evidence code

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#25]
follow on from
https://github.com/pombase/pombase-chado/issues/929

In the GO GAF  the "With/from" field sometimes has GO IDs separated by a comma.

In pombemine some appear comma separated and some appear "|" separated. They are all comma separated in the GAF (pipe separator has a different meaning- comma is a compound annotation).

**Comment by rachellyne** [comment]
We load this exactly as it is in the file that we have - some are comma-separated and some are pipe separated.

**Comment by kimrutherford** [comment]
Hi Rachel.  Which file are you loading?

The GAF file we produce each night is here: https://curation.pombase.org/dumps/latest_build/pombase-latest.gaf.gz

**Comment by rachellyne** [comment]
We are loading the file from https://www.pombase.org/downloads/go-annotations but I haven't updated it recently.   I will update with pombase-latest for next build.

**Comment by ValWood** [comment]
Fine now.
