### ISSUE TITLE
Adding 'subject ' to an allele annotation query

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#26]
I expected this to add 'gene' but  this is what I got:

<img width="769" alt="Screenshot 2022-02-01 at 09 41 25" src="https://user-images.githubusercontent.com/7359272/151945511-942cbe59-cff1-4795-ad32-0f3f56816245.png">

**Comment by rachellyne** [comment]
@ValWood  could you screenshot the query - I can't see where the subject is coming from?

**Comment by ValWood** [comment]
Right this isn't the exact query (I wasn't logged in so they didn't save)- but this is similar:

<img width="860" alt="Screenshot 2022-02-01 at 12 10 55" src="https://user-images.githubusercontent.com/7359272/151966779-6d9b011b-56f2-458f-ad1c-ff68cc8215fe.png">

We can close though, it is essentially  the same issue as https://github.com/intermine/pombemine/issues/27

**Comment by ValWood** [comment]
out of date
