### ISSUE TITLE
phenotype annotation 

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#27]
I can't seem to get from gene to phenotype annotation (It seems that only GO is available?)

- It would also be easier for users if  GO and phenotype were separate classes available from 'Gene'

**Comment by rachellyne** [comment]
@ValWood   Phenotype annotations are referenced from Alleles.  So you have to go Allele -> Phenotype annotation.

**Comment by ValWood** [comment]
> Phenotype annotations are referenced from Alleles. So you have to go Allele -> Phenotype annotation.

Right. But I would have expected to be able to then connect alleles to genes? -most users are interested in the gene that has the phenotype, even though the phenotype is (correctly) attached to the allele.

**Comment by rachellyne** [comment]
You can hide that complexity in a template.  I'll make one that connects genes directly to phenotypes.

**Comment by rachellyne** [comment]
@ValWood   http://met1.gen.private.cam.ac.uk:5050/pombemine/templates/Gene_Phenotype

Literally just contains the phenotype annotation at the moment but can configure with more columns, or make a separate more complex template.
