### ISSUE TITLE
Add enrichment for phenotypes

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#28]
The enrichment tool will be a real selling point. Can it be easily configured for phenotypes?

Also, is it possible not to show enrichment results unless a background is selected ?
Or at least configure a background?
Without a background results are provided, but they are misleading.

**Comment by rachellyne** [comment]
@ValWood   yes - it is already configured for phenotypes - I'll show you tomorrow.  We have a default background (which will be all alleles with an annotation) and you can also configure your own background (which will be an allele list).

**Comment by danielabutano** [comment]
Configure a second enrichment only for Genes

**Comment by danielabutano** [comment]
Done!
