### ISSUE TITLE
Some systematic IDs unrecognized 

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#3]
I just tried uploading the pombe proteome (systematic IDs for the
genes, attached).
Last week when I did this I got all 5057  back.
Now I only get 3730
[all_pombe_proteins.txt](https://github.com/intermine/pombemine/files/7227147/all_pombe_proteins.txt)
?

**Comment by danielabutano** [comment]
Fixed with the new build. I had use the biogrid which didn't integrate some genes
