### ISSUE TITLE
In appropriate starting classes to remove from the. menu

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#31]
Author is a valid starting point for a query, but
first name
initials
and last name

are unpopulated.

Should/could these be greyed out?

**Comment by rachellyne** [comment]
@ValWood   hmm - I am not sure why we have that class, we don't populate it.  I guess it could be added to the publication post-process which grabs all the details from PubMed.  If you start the query from Publication you can access the first author.

**Comment by danielabutano** [comment]
Not implemented yet in BG.

**Comment by ValWood** [comment]
Action: remove author from the starting classes?

**Comment by ValWood** [comment]
Closing, it is much better. I don't think anything can be done about displaying populated terms.
