### ISSUE TITLE
Chromosome

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#32]
Chromosome name is not populated.
Should this be exported in the json file?

@kimrutherford

**Comment by ValWood** [comment]
I don't know what 'score' or 'score type' mean in the context of chromosome?

**Comment by rachellyne** [comment]
Score and score type are just general fields of sequence feature.   We get extra fields like this as you can't develop a fairly generic data model and still be specific for every data type.

We tend to just use Primary identifier for chromosomes in other mines but you can add it if you want to.
