### ISSUE TITLE
Publication, no datasource loaded

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#33]
It would be useful to be able to filter the publication source  i,e PomBase  (once we provide a comprehensive list) InterPro etc.

This is required to make any publication query useful because  users will likely be interested n locating fission yeast related publications. Many of the publications are loaded by default from supporting protein families etc.

**Comment by danielabutano** [comment]
this means change the mode to add the `<collection name="dataSets" referenced-type="DataSet"/>`

**Comment by ValWood** [comment]
RIght, that works!

I did not think to look under "entities" 

also I would not know how to filter because the data sources are not obvious.  After I ran the query, I could find this information:

<img width="361" alt="Screenshot 2022-05-23 at 20 44 10" src="https://user-images.githubusercontent.com/7359272/169894648-70639f71-6824-4b78-b86b-27ff4ffdb516.png">

Could these data sources be added to a "drop down men" here because. nobody will know what to type in the look up:

<img width="572" alt="Screenshot 2022-05-23 at 20 44 28" src="https://user-images.githubusercontent.com/7359272/169894766-8aeef8a2-7dd0-4f49-8d3e-a48d64553489.png">

**Comment by ValWood** [comment]
OK, to do some troubleshooting on our publications I just tried to  build this query myself, but the template does not allow it.

In the XML  query above, which works, the  dataset is selected under "Bio-entity", but "Bio-entity" is not  available in the drop-down main menu  for "Publication" (only "Entity" which is not populated).


CC FYI
@manulera 
@kimrutherford

**Comment by kimrutherford** [comment]
> but "Bio-entity" is not available in the drop-down main menu for "Publication" (only "Entity" which is not populated).

Are you looking at the model browser?  You'll need to open up "Entities" and then select "Bio-Entity" from the drop down.  It's because `Bio-Entity` is a sub-class of `Entity`.

![pombemine-bioentity-1](https://user-images.githubusercontent.com/90474/169976364-62908c22-28d5-440f-af38-377f1bcd4f81.png)
