### ISSUE TITLE
problem with data displayed on summary pages (orthologs)

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#35]
This table presents the data type, but does not say  the ID or species of the ortholog:

<img width="1070" alt="Screenshot 2022-02-24 at 15 53 52" src="https://user-images.githubusercontent.com/7359272/155560396-a13bcc10-309b-4dd7-80d0-de9166550e0f.png">

**Comment by rachellyne** [comment]
We can configure this.  There may be a few to do.

**Comment by ValWood** [comment]
OK assigned to me.

**Comment by ValWood** [comment]
> The length is the length of that region.

Do you mean  it is the length is the distance from gene summary page feature?

**Comment by kimrutherford** [comment]
> Do you mean it is the length is the distance from gene summary page feature?

Did that go into the wrong issue?

**Comment by ValWood** [comment]
yup

**Comment by danielabutano** [comment]
Done
