### ISSUE TITLE
problem with data displayed on summary pages (Flanking regions)

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#36]
I'm not completely sure what this refers to. Is there an explanation somewhere as to what regions" are referred to? I can't figure it out.

Also most data are in the table are duplicated.
<img width="1073" alt="Screenshot 2022-02-24 at 15 53 22" src="https://user-images.githubusercontent.com/7359272/155561800-24b4bc89-bcac-465b-af13-612b7dcb8d97.png">

**Comment by ValWood** [comment]
Right. I'm not sure if this is useful for fission yeast. 
What does the 'flanking regions length' apply to ? 

Note: I think the duplication is due to all features being reported as both 'upstream' and 'downstream'.
It might make more sense once that is fixed. I'll take another look. We can decide whether to display or not

**Comment by rachellyne** [comment]
It's a post-process - as in they are calculated after the build.  It can just be removed if you don't want them.

**Comment by danielabutano** [comment]
Resolved

**Comment by danielabutano** [comment]
just remove the post process create-gene-flanking-features

**Comment by ValWood** [comment]
You can leave these in. Once the bug is resolved I can determine if they are useful
