### ISSUE TITLE
include orthologs from Panther

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#39]
~I think we chatted about adding orthologs from Diopt at some point? This would be very useful, because it would expand beyond what users can currently do with PomBase (most  types of queries can already be done).
I guess that would mean making the "PomBase curated orthologs" for S. cerevisiae and Human a "PomBase" data source, so that the different ortholog sets for human and cerevisiae could be integrated (it will be interestin for me to see the differences). 
The main value will be the ability to query for orthologs from other key species (we only link out to DIOPT, but do not load ).~

PAnther is fine

**Comment by danielabutano** [comment]
There was an inssue on the configuration. In the next build, panther orthologs shoudl be integrated too

**Comment by ValWood** [comment]
All working
