### ISSUE TITLE
allele synonyms are not loaded

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#41]
The allele synoyms column is currrently empty.

Please ping @kimrutherford  if you need any info.

**Comment by kimrutherford** [comment]
The allele synonyms aren't in the PHAF file.  I've opened an issue: pombase/pombase-chado#966

**Comment by ValWood** [comment]
ACTIONS
- [x] @kimrutherford   add synonyms to PHAF
-  [x] @danielabutano load synonyms
- [ ] @ValWood add synonym field to (some)  allele query tables.
- Useful test gene cut12 (See "All alleles of a gene" template) stf1-1 is a synonym of cut12.s11 (G71V). 
-  [ ]  @ValWood Also in current load cut12-G71V also exists. I have standardized on cut12.s11  which is the most common usage. check.

**Comment by kimrutherford** [comment]
> @kimrutherford add synonyms to PHAF

The PHAF files now have synonyms in the `Allele synonym` column:
https://curation.pombase.org/dumps/latest_build/pombase-latest.eco.phaf.gz

**Comment by kimrutherford** [comment]
> The PHAF files now have synonyms in the Allele synonym column:

I forgot to say: if there are multiple synonyms for an allele, they are pipe ("|") separated.
We chose pipes because some synonyms contain commas.

**Comment by kimrutherford** [comment]
Ah, sorry.  I thought you we getting the phenotype annotations from
https://curation.pombase.org/dumps/latest_build/pombase-latest.eco.phaf.gz
because of this issue:
https://github.com/pombase/pombase-chado/issues/869

I've now updated: https://www.pombase.org/data/annotations/Phenotype_annotations/phenotype_annotations.pombase.phaf.gz

**Comment by ValWood** [comment]
I see the allele synonyms loaded OK.
