### ISSUE TITLE
multi-allele genotypes and phenotypes

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#42]
Is there a way to load multi-allele genotypes and phenotypes? We have glossed over this data so far in our discussions but I am assuming that it is  done for some other species?

It isn't a high priority but it is something we would probably ly want to  do if it were available.

**Comment by kimrutherford** [comment]
PombeMine loads our PHAF file:
https://curation.pombase.org/dumps/latest_build/pombase-latest.eco.phaf.gz
which only contains single allele phenotypes.

Multi allele/locus export isn't implemented yet: https://github.com/pombase/curation/issues/693

**Comment by ValWood** [comment]
Yes we need  a suitable exchange format for multi-gene genotypes. I   would like to speak to @cmungall about this because we don't want to roll our own.

**Comment by kimrutherford** [comment]
We'll need to implement stable IDs for alleles and genotypes before we can export multi- locus/allele genotypes and phenotypes.

This is related: pombase/pombase-chado#840

**Comment by ValWood** [comment]
Until a format exists, this is impossible. Also not high-priority. Closing
