### ISSUE TITLE
A question, how to 'suppress'  the "gene flanking" on this search

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#49]
<img width="1196" alt="Screenshot 2022-05-18 at 14 50 03" src="https://user-images.githubusercontent.com/7359272/169086963-0b05959b-24e3-40c0-9e80-ff9a57f9c65a.png">

**Comment by danielabutano** [comment]
@ValWood I think I can configure to suppress gene flanking from the quick search

**Comment by ValWood** [comment]
I think we should do this @kimrutherford what do you think?

**Comment by kimrutherford** [comment]
I think it's definitely a good idea to suppress them from the quick search.

**Comment by ValWood** [comment]
agree

**Comment by ValWood** [comment]
We no longer see this on the main site.
