### ISSUE TITLE
SPCC548.03c  from "GO annotation dataset" (plus question, how to query the "with" filed?)

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#51]
There are 2 genes represented in pombemine  for
SPCC548.03c.01
SPCC548.03c.02

Neither @kimrutherford  or I can  figure out where these originate (they are isoform IDs but not separate genes).
We can't see where we export these. Are they coming from another source?

thanks
v

**Comment by ValWood** [comment]
I should mention that KIms  digging says this comes from: 
"GO Annotation data set"

but this is not a gene name in our annotation, it's an isoform identifier.  ...and  I can't see that we have used it in the PomBase  GO annotations.

**Comment by ValWood** [comment]
There is also another GO  data derived gene [Q9P3V0](https://beta.uniprot.org/uniprotkb/Q9P3V0)
This appears in the gene list  even.when applying the filter for taxon 4896. But it is a human gene?

**Comment by ValWood** [comment]
@kimrutherford

**Comment by kimrutherford** [comment]
> There are 2 genes represented in pombemine for
> SPCC548.03c.01
> SPCC548.03c.02

That should be:
SPCC548.03c.1
SPCC548.03c.2

One case where we use these IDs in a place that is mostly gene IDs is the "with" column of the GAF file.  For example:
```
PomBase SPCC1906.03     wtf19           GO:0005737      PMID:32032353   ISS     PomBase:SPCC548.03c.1   C       wtf meiotic drive antidote Wtf19                protein taxon:4896      20200914      PomBase part_of(CL:0000607)
PomBase SPCC1906.03     wtf19           GO:0005737      PMID:32032353   ISS     PomBase:SPCC548.03c.2   C       wtf meiotic drive antidote Wtf19                protein taxon:4896      20200914      PomBase part_of(CL:0000607)
```

Maybe they are being misunderstood as gene identifiers in that context?

**Comment by ValWood** [comment]
Right that makes sense.Hmm this is a real edge case. We can infer the location of the different specific versions of this protein (poison and antidote) , and in this case we have specified the isoform(alternative transcript) ID in the with column.

I checked the docs http://geneontology.org/docs/go-annotation-file-gaf-format-2.1/#with-or-from-column-8  to see if this field is restricted to "gene" and it isn't but isoform is not documented:


<img width="423" alt="Screenshot 2022-05-23 at 13 24 05" src="https://user-images.githubusercontent.com/7359272/169818730-2ce443a3-6e7a-456d-af6c-5a3d52b94f8d.png">


I suspect if we discussed this  the format would be the same as an allele, so it would be 
 DB:gene_symbol[isoform_symbol]

I will check this with GO

**Comment by kimrutherford** [comment]
> There is also another GO data derived gene [Q9P3V0](https://beta.uniprot.org/uniprotkb/Q9P3V0)
> This appears in the gene list even.when applying the filter for taxon 4896. But it is a human gene?

Did you paste the wrong ID?  That one (Q9P3V0) is pombe wtf4.  Did you mean Q9H9V9?

Now that I've investigated more this may be a similar problem to SPCC548.03c.1/SPCC548.03c.2

But this time it's a PomBase bug.  In the GAF file we are prefixing everything in the "with" column with "PomBase:" so we have:
```
PomBase:SPAC25H1.02             RO:0002331      GO:0002184      GO_REF:0000050  ECO:0000266     PomBase:Q9H9V9          2007-05-31      PomBase
PomBase:SPAC25H1.02             RO:0002327      GO:0106156      GO_REF:0000050  ECO:0000266     PomBase:Q9H9V9          2007-05-31      PomBase
```

It's wrong in the GPAD file too.  Whoops.

I've made an issue and I'll get to it this week: pombase/pombase-chado/issues/970

**Comment by ValWood** [comment]
> But this time it's a PomBase bug. In the GAF file we are prefixing everything in the "with" column with "PomBase:" so we have:

I don't think we can be prefixing everything (because they usually resolve on the web pages).   if we omit the prefix, PomBase must be inferred. 
I can fixed this issue in the "legacy GO annotation file"

**Comment by danielabutano** [comment]
Hi @ValWood, this query shows the genes created from the with column
![image](https://user-images.githubusercontent.com/1678179/170542058-600def76-f40e-4913-a447-9686b64c553a.png)

**Comment by danielabutano** [comment]
this query is more precise
![image](https://user-images.githubusercontent.com/1678179/170660400-59d6bd52-4e03-4c2f-bba2-eac6af4cce32.png)

below the XML if you want to import the it:
<query model="genomic" view="GOEvidence.withText GOEvidence.with.name GOEvidence.with.primaryIdentifier GOEvidence.with.dataSets.name" constraintLogic="(A)" sortOrder="">
   <constraint path="GOEvidence.with.dataSets.name" op="NONE OF" code="A"><value>Pombe-gene data set</value><value>cerevisiae-orthologs data set</value><value>human-orthologs data set</value><value>BioGRID interaction data set</value><value>PomBase disease data set</value><value>PomBase phenotypes data set</value></constraint>
</query>

**Comment by ValWood** [comment]
Got it. I forgot I need to switch to "GO evidence"
