### ISSUE TITLE
Can we make queries through the HTTP API

### ISSUE THREAD

**Issue by manulera** [intermine/pombemine#56]
Hello, I am Manu I work in Pombase as well.

I wanted to ask you if it's possible to make a query through http, if we have the query xml.

**Comment by danielabutano** [comment]
Hi @manulera 
yes you can, something like
`http://pombemine.rahtiapp.fi/pombemine/service/query/results?query={your xml query}&format={json, tsv, xml}&size=10`
More details in the docuementation [here](http://iodocs.apps.intermine.org/)
The new frontend doesn't not provide yet the _Web Service URL_ link (similar to the button in the template)

![image](https://user-images.githubusercontent.com/1678179/170699157-187afb4f-b987-4b11-a69c-b6ccf05449ef.png)

**Comment by danielabutano** [comment]
@manulera If I have answered your question, could you please close the ticket? Thanks!

**Comment by manulera** [comment]
Hi @danielabutano sorry for the late reply. I have been meaning to try it but I kept postponing.

That's what I had tried, but it kept not working. I realised the problem for me was that I had left the `\n` in the xml string. I had to run the `strip()` command on the string and then it worked. I suppose this can be a common issue if people have stored their queries in xml files. Maybe this is obvious for someone working often with xml. A working example in python, in case:

```python
import requests

query = """
<query model="genomic" view="Gene.primaryIdentifier Gene.symbol Gene.organism.species Gene.alleles.primaryIdentifier Gene.alleles.description Gene.alleles.expression" constraintLogic="(A)" sortOrder="">
   <constraint path="Gene.organism.species" value="pombe" op="=" code="A"/>
</query>
"""
query = query.strip()

response = requests.get(
    f'http://pombemine.rahtiapp.fi/pombemine/service/query/results?query={query}&format={"tsv"}&size=10'
)

print(response.status_code)
print(response._content)
```
