### ISSUE TITLE
Modelling penetrance and severity

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#57]
Penetrance is displayed almost perfectly.  Penetrance curation  is a bit complicated by the fact that it can be a number, number range (percentage) or by a qualitative value "high" medium" or "low".

This is how it looks currently in the query output:
<img width="1096" alt="Screenshot 2022-05-30 at 15 02 02" src="https://user-images.githubusercontent.com/7359272/171009758-40a01ba0-2806-4864-b071-4522515811cc.png">
I think this works with the column headings.

For convenience, in PomBase, to make it easier to store the qualitative values in Chado, we converted these values to a "mini-ontology". However at PomBAse our users never see this. They only see the values.
So, we should convert these into the  text strings that they represent as follows:
FYPO_EXT:0000001 = high
FYPO_EXT:0000002 = medium
FYPO_EXT:0000003 = low

This raises a question (for @kimrutherford ). Should these qualifiers be converted during loading into PomBemine. OR
should we change  export the text in the PHAF file instead of the IDs? Exporting the values might make more sense to all consumers of the PHAF file  than the ontology term ID. This was really a workaround to make it easy to curate these   annotation "qualifiers" rather than something that needed to be represented in an ontology with definitions etc?

**Comment by ValWood** [comment]
"Severity" is a qualifier very similar to penetrance *except* in this case there is only the text values "low" "medium" and high".
It should be modelled in the same way as penetrance.
Currrently it is modelled in a more complicated way:

<img width="596" alt="Screenshot 2022-05-30 at 15 22 53" src="https://user-images.githubusercontent.com/7359272/171012484-dab98195-c6d3-4f63-b9ce-03eb762f63f6.png">

and
<img width="281" alt="Screenshot 2022-05-30 at 15 24 16" src="https://user-images.githubusercontent.com/7359272/171012615-0db0eb0b-a46e-4ffd-80a7-de8e162e59af.png">

For this we only need to store the qualifier value (Low, medium or high) as for penetrance above.
Also the description of these terms does not make sense (it applies to both penetrance and severity, because we use the same "fake ontology" to store the values.

Apologies for not spotting this before. I only just figured out what was going on.

**Comment by kimrutherford** [comment]
> Should these qualifiers be converted during loading into PomBemine. OR
> should we change export the text in the PHAF file instead of the IDs? Exporting the values might make more sense to all
> consumers of the PHAF file than the ontology term ID.

I think it would be OK to use "low", "high" etc. in the PHAF file.  The Penetrance column already contains a bunch of non-term ID values (like "13" and "~82").

I've made a separate issue about it: pombase/pombase-chado#978

**Comment by ValWood** [comment]
OK that makes sense, it will make it simpler for @danielabutano

**Comment by kimrutherford** [comment]
> I think it would be OK to use "low", "high" etc. in the PHAF file. The Penetrance column already contains a bunch of non-term ID values (like "13" and "~82").

That's done now, so both PHAF files have term names instead of term IDs for penetrance and severity:
  - https://curation.pombase.org/dumps/latest_build/pombase-latest.eco.phaf.gz
  - https://curation.pombase.org/dumps/latest_build/pombase-latest.phaf.gz

**Comment by danielabutano** [comment]
Ok, I will change the model so both penetrance and severity will be String with value loaded directly from https://www.pombase.org/data/annotations/Phenotype_annotations
`<class name="PhenotypeAnnotation" extends="OntologyAnnotation" is-interface="true">
    <attribute name="penetrance" type="java.lang.String"/>
    <attribute name="severity" type="java.lang.String"/>
    ........
  </class>`

**Comment by ValWood** [comment]
Perfect, both penetracne and severity are showing high, medium, low. Pentrance is also displaying percentage.
