### ISSUE TITLE
Question:  How to access protein domain beginning from gene?

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#61]
I can't see how to do this.  I also can't access gene from domain due to an apparent bug:
https://github.com/intermine/bluegenes/issues/799

**Comment by ValWood** [comment]
So protein domains are loaded  from secondary source (UniProt) rather than primary source (InterPro)? (this will make them quite out of data. as UniProt only updates every 6 months or so). Also it in not clear if this will include protein families as well as domains. 

It's OK for now. This is just an observation.

**Comment by danielabutano** [comment]
@ValWood Protein domain and ProteinDomainRegion are loaded from InterPro.
Gene -> UniProtEntry->ProteinDomainRegion->ProteinDomain was only a way to show you how the relation between gene and protein domain has been implemented in the intermine model.
If it might helpful to look at the template [Gene -> Protein + Domains](https://www.humanmine.org/humanmine/templates/Gene_proteindomain) defined in humanmine.
Let me know if I have I 've misundersdood your question.

**Comment by ValWood** [comment]
THANKS!
