### ISSUE TITLE
Gene list upload doesn't work with "Any" from the organism selector

### ISSUE THREAD

**Issue by kimrutherford** [intermine/pombemine#67]
If I paste in some pombe IDs, but leave the organism selector on "Any", no genes are found:

![image](https://user-images.githubusercontent.com/90474/174712120-d659a078-1cf8-4686-be84-8004a4696ff2.png)

Also it says "Gene list for D. melanogaster ...":

![image](https://user-images.githubusercontent.com/90474/174712251-a755c037-a4de-4d4d-abcd-0b93c188b514.png)

**Comment by ValWood** [comment]
On the BJ tracker
https://github.com/intermine/bluegenes/issues/808
This is fixed, pending release.
