### ISSUE TITLE
Set up Google Analytics

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#71]
required for release.

**Comment by danielabutano** [comment]
Hi @kimrutherford , @heralden has update BG to work with google analytics (see https://github.com/intermine/bluegenes/issues/832)
We need to register for google analytics. After creating the property, and a new data stream, turn off enhanced measurement and copy the G-* measurement ID for use as GOOGLE_ANALYTICS config var.
I can add the GOOGLE_ANALYTICS config var to BG, @kimrutherford can you do the rest?

**Comment by kimrutherford** [comment]
Thanks Daniela.  I've added a new property and stream.  The ID is G-VWL4P0C0CE.  Is that all you need?

**Comment by danielabutano** [comment]
thanks @kimrutherford . I will add the ID

**Comment by danielabutano** [comment]
Hi @kimrutherford, I have added the gogle id and updated BG. you can test it

**Comment by kimrutherford** [comment]
Thanks very much Daniela.  It seems to be working!

(Val, I'll send you a link separately)

**Comment by heralden** [comment]
@kimrutherford @ValWood If you have ideas for new tracking events, please comment in this issue: https://github.com/intermine/bluegenes/issues/835
Your feedback would be useful as you're the first real-world user of the analytics.
