### ISSUE TITLE
publication information renders oddly

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#8]
See:

<img width="1338" alt="Screenshot 2021-11-15 at 14 44 18" src="https://user-images.githubusercontent.com/7359272/141802250-58bdb709-bd12-4751-b0e1-1a665034d47e.png">

**Comment by rachellyne** [comment]
Agree it's not the best!  It's not much better in the BlueGenes interface.  I'll talk with Kevin and see if we can rearrange the display at all.  We have the same problem in FlyMine and HumanMine.  I think it's just because the abstract text is so long.

**Comment by rachellyne** [comment]
Kevin already has a ticket for this and plans to fix in the next release.
