### ISSUE TITLE
"click to see examples" examples don't match 'type'

### ISSUE THREAD

**Issue by ValWood** [intermine/pombemine#9]
For example here:
I expected to see  domain syntax example rather than 'genes'
<img width="620" alt="Screenshot 2021-11-15 at 14 47 15" src="https://user-images.githubusercontent.com/7359272/141802546-727a3d41-d761-4701-9f97-d9e96329e9ee.png">

**Comment by rachellyne** [comment]
How did you get  "Protein domain".  It should definitely be Gene.  I don't get anything set for the type.  This hasn't been configured yet for pombemine but we usually just have an example set of genes.

**Comment by danielabutano** [comment]
I have udated the configuration adding a few pombe genes:
SPAC24B11.06c, SPBC83.18c, SPAC1071.12c, SPAC11D3.03c, SPAC11E3.06, SPAC11D3.04c, SPAC1093.02, SPAC1039.10, SPAC10F6.17c, SPAC11E3.07

**Comment by ValWood** [comment]
Do we need different lists for the different datatypes?
